### ISSUE TITLE
Language selector in the login screen does not work

### ISSUE THREAD

**Issue by gjong** [pledger-io/user-interface#16]
**Describe the bug**
When selecting another language on the login screen the actual language of the UI does not change.

**To Reproduce**
1. Go to login
2. Click on the language selector
3. Change the language

**Comment by Elaa257** [comment]
@gjong Hi, do you need help solving this issue? If so, I would like to do this as my first issue :)

**Comment by agusaar** [comment]
If, it's not solved, i would like to work on it
